version: "3"
services:
  islam_app:
    container_name: islam_app_src
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: islam_app_db
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5433:5432"
